; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\_build\main.o --depend=.\_build\main.d --cpu=Cortex-M0 --apcs=interwork -O3 --diag_suppress=9931 -I..\..\.. -I.\RTE\_nrf51422_xxac -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\4.5.0\CMSIS\Include -IC:\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_DeviceFamilyPack\8.3.1\Device\Include -IC:\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_Drivers\4.0.0-2.alpha\delay -IC:\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_Drivers\4.0.0-2.alpha\hal -IC:\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_Examples\11.0.0-2.alpha\bsp -D__MICROLIB -D__UVISION_VERSION=524 -D_RTE_ -DNRF51 -DBSP_DEFINES_ONLY -DBOARD_PCA10028 -DNRF51 --omf_browse=.\_build\main.crf main.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.crypto_hash||, CODE, READONLY, ALIGN=1

crypto_hash PROC
        PUSH     {r4-r7,lr}
        MOV      r4,r2
        MOV      r7,r1
        SUB      sp,sp,#0x1a4
        MOV      r6,r0
        MOVS     r2,#0xff
        MOVS     r1,#9
        MOV      r5,r3
        ADDS     r2,r2,#0xc1
        LSLS     r1,r1,#7
        MOV      r0,sp
        BL       InitSponge
        LSRS     r0,r4,#29
        LSLS     r3,r5,#3
        ORRS     r3,r3,r0
        LSLS     r2,r4,#3
        MOV      r1,r7
        MOV      r0,sp
        BL       Absorb
        MOVS     r2,#7
        LSLS     r2,r2,#9
        MOVS     r3,#0
        MOV      r1,r6
        MOV      r0,sp
        BL       Squeeze
        MOVS     r0,#0
        ADD      sp,sp,#0x1a4
        POP      {r4-r7,pc}
        ENDP


        AREA ||i.main||, CODE, READONLY, ALIGN=2

main PROC
        SUB      sp,sp,#0x1fc
        SUB      sp,sp,#0x1fc
        MOVS     r0,#0
        MOVS     r1,#1
        LDR      r3,|L2.104|
        SUB      sp,sp,#0x1c8
        MOVS     r2,#3
|L2.14|
        MOV      r4,r1
        LSLS     r4,r4,r0
        LSLS     r4,r4,#9
        LSRS     r4,r4,#27
        BEQ      |L2.30|
        LSLS     r4,r0,#2
        ADDS     r4,r4,r3
        STR      r2,[r4,#0]
|L2.30|
        ADDS     r0,r0,#1
        CMP      r0,#0x20
        BCC      |L2.14|
        MOVS     r0,#0
        MOVS     r6,#1
        MOV      r7,sp
        LSLS     r6,r6,#10
|L2.44|
        STRB     r0,[r7,r0]
        ADDS     r0,r0,#1
        CMP      r0,r6
        BLT      |L2.44|
        LDR      r4,|L2.108|
        MOVS     r5,#1
        LSLS     r5,r5,#19
|L2.58|
        LDR      r0,[r4,#4]
        MOV      r1,r5
        BICS     r1,r1,r0
        STR      r1,[r4,#8]
        ANDS     r0,r0,r5
        STR      r0,[r4,#0xc]
        ADD      r0,sp,#0x3fc
        MOV      r2,r6
        MOVS     r3,#0
        MOV      r1,r7
        ADDS     r0,#4
        BL       crypto_hash
        LDR      r0,[r4,#4]
        MOV      r1,r5
        BICS     r1,r1,r0
        STR      r1,[r4,#8]
        ANDS     r0,r0,r5
        STR      r0,[r4,#0xc]
        MOVS     r0,#0xa
        BL       nrf_delay_ms
        B        |L2.58|
        ENDP

|L2.104|
        DCD      0x50000700
|L2.108|
        DCD      0x50000500

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.constdata||, DATA, READONLY, ALIGN=0

leds_list
        DCB      0x12,0x13,0x14,0x15
        DCB      0x16

;*** Start embedded assembler ***

#line 1 "main.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_e9d5a046____REV16|
#line 388 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___6_main_c_e9d5a046____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_e9d5a046____REVSH|
#line 402
|__asm___6_main_c_e9d5a046____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_e9d5a046__nrf_delay_us|
#line 16 "C:\\Keil_v5\\ARM\\PACK\\NordicSemiconductor\\nRF_Drivers\\4.0.0-2.alpha\\delay\\nrf_delay.h"
|__asm___6_main_c_e9d5a046__nrf_delay_us| PROC
#line 17

loop
 SUBS R0, R0, #1
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
#line 77

 BNE loop
 BX LR
	ENDP

;*** End   embedded assembler ***

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT crypto_hash [CODE]
        EXPORT main [CODE]
        EXPORT leds_list [DATA,SIZE=5]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT InitSponge [CODE]
        IMPORT Absorb [CODE]
        IMPORT Squeeze [CODE]
        IMPORT nrf_delay_ms [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
