; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\_build\nrf_delay.o --depend=.\_build\nrf_delay.d --cpu=Cortex-M0 --apcs=interwork -O3 --diag_suppress=9931 -I..\..\.. -I.\RTE\_nrf51422_xxac -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\4.5.0\CMSIS\Include -IC:\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_DeviceFamilyPack\8.3.1\Device\Include -IC:\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_Drivers\4.0.0-2.alpha\delay -IC:\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_Drivers\4.0.0-2.alpha\hal -IC:\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_Examples\11.0.0-2.alpha\bsp -D__MICROLIB -D__UVISION_VERSION=524 -D_RTE_ -DNRF51 -DBSP_DEFINES_ONLY -DBOARD_PCA10028 -DNRF51 --omf_browse=.\_build\nrf_delay.crf C:\Keil_v5\ARM\PACK\NordicSemiconductor\nRF_Drivers\4.0.0-2.alpha\delay\nrf_delay.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.nrf_delay_ms||, CODE, READONLY, ALIGN=2

nrf_delay_ms PROC
        PUSH     {r0,r4,r5,lr}
        LDR      r4,|L1.24|
        B        |L1.16|
|L1.6|
        SUBS     r0,r0,#1
        STR      r0,[sp,#0]
        MOV      r0,r4
        BL       __asm___11_nrf_delay_c_532987f3__nrf_delay_us
|L1.16|
        LDR      r0,[sp,#0]
        CMP      r0,#0
        BNE      |L1.6|
        POP      {r3-r5,pc}
        ENDP

|L1.24|
        DCD      0x000003e7

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "C:\\Keil_v5\\ARM\\PACK\\NordicSemiconductor\\nRF_Drivers\\4.0.0-2.alpha\\delay\\nrf_delay.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___11_nrf_delay_c_532987f3____REV16|
#line 388 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___11_nrf_delay_c_532987f3____REV16| PROC
#line 389

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___11_nrf_delay_c_532987f3____REVSH|
#line 402
|__asm___11_nrf_delay_c_532987f3____REVSH| PROC
#line 403

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE
	THUMB
	EXPORT |__asm___11_nrf_delay_c_532987f3__nrf_delay_us|
#line 16 "C:\\Keil_v5\\ARM\\PACK\\NordicSemiconductor\\nRF_Drivers\\4.0.0-2.alpha\\delay\\nrf_delay.h"
|__asm___11_nrf_delay_c_532987f3__nrf_delay_us| PROC
#line 17

loop
 SUBS R0, R0, #1
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
 NOP
#line 77

 BNE loop
 BX LR
	ENDP

;*** End   embedded assembler ***

        EXPORT nrf_delay_ms [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
